### ISSUE TITLE
Error when using webpack, uglify and snapshot

### ISSUE THREAD

**Issue by madsongr** [shripalsoni04/nativescript-material-icons#3]
I was following this https://docs.nativescript.org/angular/best-practices/startup-times.html article to speed up my app startup ({N} + angular) and everything was fine during the installation.

When I tried running npm run start-android-bundle --uglify --snapshot I got some errors and I noticed that it was because of "TNSFontIconModule" in app.module.ts what is causing a problem in app.css too.

Below are the errors and I would appreciate some help. 

```
[264] ./app.css 4.93 kB {1} [built] [failed] [1 error]
    + 258 hidden modules

ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule', function calls are not supported.
Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/Mobile Develop/Nat
iveScript/LoginSystem/app/app.module.ts, resolving symbol AppModule in D:/Mobile Develop/NativeScript/LoginSystem/app/app.module.ts

ERROR in ./app.css
Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
    at error (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:37:11)
    at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:222:9
    at Array.forEach (native)
    at browserslist (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:196:13)
    at cleanBrowsersList (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\utils.js:56:59)
    at setBrowserScope (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\index.js:29:43)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\index.js:91:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:
7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\postcss-merge-rules\dist\index.js:21:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

ERROR in ./app.css
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" |
sed -e 's,\\,/,g')")`
    at error (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:37:11)
    at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:222:9
    at Array.forEach (native)
    at browserslist (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:196:13)
    at cleanBrowsersList (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\utils.js:56:59)
    at setBrowserScope (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\index.js:29:43)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\index.js:91:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:
7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\postcss-merge-rules\dist\index.js:21:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at runLoaders (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModule.js:193:19)
    at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModule.js:180:3)
    at NormalModule.build (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModule.js:273:15)
    at Compilation.buildModule (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\Compilation.js:145:10)
    at moduleFactory.create (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\Compilation.js:432:9)
    at factory (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModuleFactory.js:99:14)
    at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\tapable\lib\Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\Compa
tibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\tapable\lib\Tapable.js:2
72:13)
    at resolver (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModuleFactory.js:74:11)
    at process.nextTick (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\webpack\lib\NormalModuleFactory.js:205:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Child extract-text-webpack-plugin D:\Mobile Develop\NativeScript\LoginSystem\node_modules\extract-text-webpack-plugin\dist D:\Mobile De
velop\NativeScript\LoginSystem\node_modules\resolve-url-loader\index.js??ref--1-1!D:\Mobile Develop\NativeScript\LoginSystem\node_modul
es\nativescript-css-loader\index.js??ref--1-2!D:\Mobile Develop\NativeScript\LoginSystem\node_modules\nativescript-dev-webpack\platform
-css-loader.js!D:\Mobile Develop\NativeScript\LoginSystem\app\app.css:
       [0] ../node_modules/resolve-url-loader?{"silent":true}!../node_modules/nativescript-css-loader?{"minimize":false}!../node_module
s/nativescript-dev-webpack/platform-css-loader.js!./app.css 2.08 kB {0} [built] [failed] [1 error]

    ERROR in ../node_modules/resolve-url-loader?{"silent":true}!../node_modules/nativescript-css-loader?{"minimize":false}!../node_modu
les/nativescript-dev-webpack/platform-css-loader.js!./app.css
    Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
        at error (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:37:11)
        at D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:222:9
        at Array.forEach (native)
        at browserslist (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\browserslist\index.js:196:13)
        at cleanBrowsersList (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\utils.js:56:59)
        at setBrowserScope (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\index.js:29:43)
        at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\caniuse-api\dist\index.js:91:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility
.js:7:19)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\Mobile Develop\NativeScript\LoginSystem\node_modules\postcss-merge-rules\dist\index.js:21:28)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
Webpack Bundle Analyzer saved stats file to D:\Mobile Develop\NativeScript\LoginSystem\report\stats.json
Webpack Bundle Analyzer saved report to D:\Mobile Develop\NativeScript\LoginSystem\report\report.html
child process exited with code 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madson_gr\AppData\Roaming\npm-cache\_logs\2017-10-14T20_50_50_510Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build-android-bundle: `npm run ns-bundle --android --build-app`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madson_gr\AppData\Roaming\npm-cache\_logs\2017-10-14T20_50_51_459Z-debug.log

```

**Comment by SP1966** [comment]
I'm not actually seeing this error, but when I do build with Webpack the icon-fonts are not shown. 

Is this repo still being maintained?

**Comment by madsongr** [comment]
@SP1966 try to uninstall ng2 and install ngx version like discussed here: 
https://github.com/NativeScript/nativescript-angular/issues/1040

**Comment by anki247** [comment]
Little bit late, but if someone still runs to this issue...

Steps I had to do
1. npm i --save nativescript-ngx-fonticon@4.1.0 (some how there is problems with the current version 4.2) instead of `nativescript-ng2-fonticon don´t forget to update the import from refs!
2. create a new folder `/app/assets`
3. move `material-design-icons.css` into the new `assets` folder
4. adapt the `imports` like that `TNSFontIconModule.forRoot({ 'mdi': './assets/material-design-icons.css' })`
5. Adapt the CopyWebpackPlugin part of webpack.config.js
````javascript
new CopyWebpackPlugin([
    { from: "assets/**"},
    ....
 ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
`````
